### ISSUE TITLE
TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by Dtappledoghuati** [iduta/pyconv#8]
I moved your convolutional layer into another model for training, but the following problems occurred:

Traceback (most recent call last):
  File "main_reid.py", line 203, in <module>
    fire.Fire()
  File "/home/misstian/anaconda3/envs/reid/lib/python3.6/site-packages/fire/core.py", line 138, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/misstian/anaconda3/envs/reid/lib/python3.6/site-packages/fire/core.py", line 468, in _Fire
    target=component.__name__)
  File "/home/misstian/anaconda3/envs/reid/lib/python3.6/site-packages/fire/core.py", line 672, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "main_reid.py", line 164, in train
    reid_trainer.train(epoch, trainloader)
  File "/media/misstian/tnq/er/trainers/trainer.py", line 34, in train
    self._forward()
  File "/media/misstian/tnq/er/trainers/trainer.py", line 91, in _forward
    score, feat = self.model(self.data)
  File "/home/misstian/anaconda3/envs/reid/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/misstian/anaconda3/envs/reid/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 150, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/misstian/anaconda3/envs/reid/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/misstian/tnq/er/models/networks.py", line 196, in forward
    x = self.backbone(x)
  File "/home/misstian/anaconda3/envs/reid/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/misstian/anaconda3/envs/reid/lib/python3.6/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/misstian/anaconda3/envs/reid/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/misstian/anaconda3/envs/reid/lib/python3.6/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/misstian/anaconda3/envs/reid/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/misstian/tnq/er/models/resnet.py", line 142, in forward
    out = self.conv2(out)
TypeError: 'NoneType' object is not callable

Do you have good suggestions?

**Comment by iduta** [comment]
If you did not try already, you can use as a starting point our PyConv2d from https://github.com/iduta/pyconv/blob/master/models/pyconvresnet.py
You can find there an example.
